---
- name: Create admin group
  ansible.builtin.group:
    name: admin
    state: present
  become: true

- name: Create admin directory
  ansible.builtin.file:
    path: /home/admin
    state: directory
    mode: '0775'
    group: admin
  become: true

- name: "Adjust user accounts"
  ansible.builtin.user:
    name: "{{ item }}"
    groups: sudo,admin
    append: true
    shell: "/bin/bash"
  loop: "{{ users }}"
  become: true

- name: "Create link to admin directory"
  ansible.builtin.file:
    src: /home/admin
    dest: "/home/{{ item }}/admin"
    state: link
  loop: "{{ users }}"
  become: true

- name: "Create root link to admin directory"
  ansible.builtin.file:
    src: /home/admin
    dest: "/root/admin"
    state: link
  become: true

# https://luiscachog.io/using-the-ansible-stat-module-on-a-loop/
- name: "Check if .bashrc exists"
  ansible.builtin.stat:
    path: "/home/{{ username }}/.bashrc"
  loop_control:
    loop_var: username
  register: bashrc
  loop: "{{ users }}"
  become: true

- name: "Create .bashrc"
  ansible.builtin.file:
    dest: "/home/{{ item.username }}/.bashrc"
    state: "{{ 'file' if item.stat.exists else 'touch' }}"
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: "644"
  loop: "{{ bashrc.results }}"
  become: true

- name: "Add dc alias to .bashrc"
  ansible.builtin.lineinfile:
    path: "/home/{{ item }}/.bashrc"
    insertafter: EOF
    line: alias dc="sudo docker compose"
  loop: "{{ users }}"
  when: docker
  become: true

- name: "Change root's .bashrc"
  ansible.builtin.template:
    remote_src: true
    src: /etc/skel/.bashrc
    dest: /root/.bashrc
    mode: '644'
  become: true
