---
- name: "Create docker config directory"
  ansible.builtin.file:
    path: /etc/docker/
    state: directory
    mode: '0775'
  become: true

- name: "Adjusting /etc/docker/daemon.json"
  ansible.builtin.template:
    src: docker-daemon.json
    dest: /etc/docker/daemon.json
    mode: '644'
  register: replace_docker_daemon_json
  become: true

- name: Populate service facts
  ansible.builtin.service_facts:

# TODO think about creating a handler
- name: "Restart docker daemon to apply changes in /etc/docker/daemon.json"
  ansible.builtin.systemd:
    name: docker
    state: restarted
  when: "'docker' in services and replace_docker_daemon_json.changed"
  become: true
