---
- name: Install requirements
  ansible.builtin.apt:
    update_cache: true
    name:
      - curl
      - cron
    state: present
  become: true

- name: Install acme.sh
  ansible.builtin.command: "sh -c 'curl -fsSL https://get.acme.sh | sh -s email={{ nginx_cert_email }}'"
  become: true

- name: Link acme.sh to /usr/bin
  ansible.builtin.file:
    src: /root/.acme.sh/acme.sh
    dest: /usr/bin/acme.sh
    state: link
  become: true

- name: Set lets encrypt backend for acme.sh
  ansible.builtin.command: |
    /root/.acme.sh/acme.sh --server https://acme-v02.api.letsencrypt.org/directory --set-default-ca
  become: true
