---
- hosts: all
  vars_files:
    - .operator.yaml

  pre_tasks:

    - name: Install tools and requirements
      ansible.builtin.apt:
        update_cache: true
        name:
          - python3-requests
          - python3-apt
          - curl
          - wget
          - dnsutils
          - mtr
          - tcpdump
          - ncdu
          - jq
          - iptables
          - iptables-persistent
        state: present
      become: true

    - name: Download genpw
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/felbinger/scripts/master/genpw.sh
        dest: /usr/local/bin/genpw
        mode: '755'
      become: true

    - name: Remove motd
      ansible.builtin.copy:
        content: ""
        dest: /etc/motd
        mode: '0644'
      become: true

    - ansible.builtin.include_tasks: tasks/fix-permission.yaml

    - ansible.builtin.include_tasks: tasks/docker-deamon.yaml
      when: docker and adjust_docker_deamon

  roles:
    - role: roles/ansible-role-docker
      when: docker
      tags:
        - docker
      become: true

    - role: roles/ansible-role-adminguide_nginx
      when: nginx
      tags:
        - nginx

  post_tasks:
    - ansible.builtin.include_tasks: tasks/adjust-users.yaml

    - name: Install docker compose
      ansible.builtin.apt:
        update_cache: true
        name:
          - docker-compose-plugin
        state: present
      when: docker
      tags: docker
      become: true
